import { test, expect } from '@playwright/test';

const billingAddressContinue = '//*[@id="billing-buttons-container"]//input';
const shippingAddressContinue = '//*[@id="shipping-buttons-container"]//input';
const shippingMethodContinue =  '//*[@id="shipping-method-buttons-container"]//input';
const paymentMethodContinue =   '//*[@id="payment-method-buttons-container"]//input';
const paymentInfoContinue = '//*[@id="payment-info-buttons-container"]//input';

test('@testtres - test', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('t3st3rqa@gmail.com');
  await page.getByLabel('Password:').click();
  await page.getByLabel('Password:').fill('123tester');
  await page.getByRole('button', { name: 'Log in' }).click();
  // await expect(page.locator('body')).toContainText('t3st3rqa@gmail.com');
  // await page.getByRole('link', { name: 'Apparel & Shoes' }).first().click();
  // await page.getByRole('link', { name: 'Blue Jeans', exact: true }).click();
  // await page.locator('.product-price').click();
  // await expect(page.locator('#product-details-form')).toContainText('1.00');
  // await page.getByLabel('Qty:').click();
  // await page.getByLabel('Qty:').fill('25');
  // await page.locator('#add-to-cart-button-36').click();
  // await expect(page.getByText('The product has been added to')).toBeVisible();
  // await expect(page.locator('#bar-notification')).toContainText('The product has been added to your shopping cart');
  await page.getByRole('link', { name: /Shopping cart \(\d+\)/i }).click();
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.locator(billingAddressContinue).waitFor();
  await page.locator(billingAddressContinue).click();
  await page.locator(shippingAddressContinue).waitFor();
  await page.locator(shippingAddressContinue).click();
  await page.locator(shippingMethodContinue).waitFor();
  await page.locator(shippingMethodContinue).click();
  await page.getByLabel('Credit Card').check();
  await page.locator(paymentMethodContinue).waitFor();
  await page.locator(paymentMethodContinue).click();
  await page.locator('#CreditCardType').selectOption('MasterCard');
  await page.getByLabel('Cardholder name').click();
  await page.getByLabel('Cardholder name').fill('Tester QA');
  await page.getByLabel('Card number').click();
  await page.getByLabel('Card number').fill('4000300020001000');
  await page.getByLabel('Expiration date').selectOption('7');
  await page.locator('#ExpireYear').selectOption('2034');
  await page.getByLabel('Card code').click();
  await page.getByLabel('Card code').fill('321');
  await page.locator(paymentInfoContinue).waitFor();
  await page.locator(paymentInfoContinue).click();
  await expect(page.locator('#checkout-confirm-order-load')).toContainText('25');
  await expect(page.locator('#checkout-confirm-order-load')).toContainText('25.00');
  await expect(page.locator('#checkout-confirm-order-load')).toContainText('35.00');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.goto('https://demowebshop.tricentis.com/checkout/completed/');
  await expect(page.locator('body')).toContainText('Your order has been successfully processed!');
  await page.getByText('Order number:').click();
  await expect(page.locator('body')).toContainText('Order number: 1665674');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('link', { name: 'Log out' }).click();
  await expect(page.getByRole('link', { name: 'Log in' })).toBeVisible();
});